//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicholsonFamilyFarm.Entity.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int InventoryId { get; set; }
        public System.DateTime Date { get; set; }
        public int NoOfEggs { get; set; }
        public int AccountId { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
