//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicholsonFamilyFarm.Entity.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int NoOfEggs { get; set; }
        public decimal Amount { get; set; }
        public string Status { get; set; }
        public int CustomerId { get; set; }
        public int AccountId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
